### ISSUE TITLE
The UI has a hard-coded endpoint that doesn't work with custom config

### ISSUE THREAD

**Issue by stasadev** [PacoVK/sqs-admin#475]
The backend API endpoint is hard-coded to `http://localhost:3999`.

There is no way to use a different host, and you cannot use a different `HTTP_PORT` if the frontend always points you to `3999`.

Is it possible to add it to the list of env variables?

See:
- https://github.com/PacoVK/sqs-admin/blob/main/frontend/config.json

**Comment by PacoVK** [comment]
Currently you just can overwrite the port in development mode. This is mainly because the frontend gets bundled on build and since React will run on the client side, env variables won't have an effect. 
Since frontend and backend are running on the same host there is no need to change this. What is your exact use case to change this?

**Comment by PacoVK** [comment]
Thank you for explanation and the PR!
