### ISSUE TITLE
Use the javascript AWS Client instead of Go server

### ISSUE THREAD

**Issue by AlejandroPerez92** [PacoVK/sqs-admin#626]
Using the package directly in the app could significantly improve the developer experience and, of course, reduce the code to maintain. I was doing some tests, and it can work, but the counterpoint is that Localstack needs to allow localhost URLs in the CORS settings (You can do it with an environment variable).
This change could open the door to porting the app to Electron.

What do you think? Could It be a good idea?

**Comment by PacoVK** [comment]
While i agree with you, the overall design principle was to provide the UI compatible with already existing developer setups. Using Localstack, most likely the dev stack is Docker/ container-based. Thus SQS-Admin is just another container. Electron would need the devs to install more software on they local machine. There would also be the need to provide ability to configure the Localstack host/ port, apart from the CORS settings. 
I could have provided all as SPA without the server component but using client JS sdk, that would have meant the SPA would be built during container startup, which is also tricky because you'll loose imutability of the artefact. :)

**Comment by AlejandroPerez92** [comment]
Yeah, I agree with you, running it inside a container is more user-friendly. Anyway, we can pre-build the SPA, configure the connection inside the app, and persist it in session storage.
